export const PERSONAL = {
  name: 'Mustakim Shikalgar',
  title: 'Software Engineer',
  tagline: 'Building distributed systems and intelligent applications.',
  bio: 'MS Software Engineering student at Arizona State University (GPA 3.75), graduating May 2026. Published IEEE researcher, Technical Architecture Lead, and top 15% LeetCode solver. I work at the intersection of distributed systems, machine learning, and full-stack engineering.',
  email: 'shikalgar.mustakim@gmail.com',
  linkedin: 'https://www.linkedin.com/in/mustakim-shikalgar',
  github: 'https://github.com/MustakimFS',
  leetcode: 'https://leetcode.com/u/Mustakim_Shikalgar/',
  ieee: 'https://ieeexplore.ieee.org/document/11126748',
  resume: '/resume.pdf',
  location: 'Tempe, Arizona',
}

export const PROJECTS = [
  {
    id: 'mety-legal',
    title: 'METY Legal Chatbot',
    subtitle: 'LangGraph · Django · React · FastAPI',
    description: 'AI legal assistant (industry capstone, contract) with two user modes, guided learning and direct help. Rebuilt the LangGraph pipeline from 6 nodes to 5, cutting LLM calls per message from 2 to 1. Implemented FSPR knowledge profiling, lawyer-style probing behavior, and rolling conversation summarization for coherent long-session context retention.',
    metrics: [
      { label: 'Cost per query', value: '$0.0008' },
      { label: 'Cost reduction', value: '85%' },
      { label: 'Legal domains', value: '9' },
    ],
    tags: ['LangGraph', 'Django', 'React', 'FastAPI', 'MongoDB', 'GPT-4o-mini'],
    github: null,
    demo: null,
    featured: true,
    category: 'AI / Full Stack',
    note: 'Private contract project — source code under NDA',
  },
  {
    id: 'distributed-kv',
    title: 'Distributed Key-Value Store',
    subtitle: 'Raft Consensus · gRPC · Java · Docker',
    description: 'Fault-tolerant distributed KV store implementing Raft consensus for leader election and log replication across a 5-node cluster. Tunable consistency supporting CP vs AP trade-offs via configurable quorum-based reads.',
    metrics: [
      { label: 'Cluster nodes', value: '5' },
      { label: 'Read latency', value: '<10ms' },
      { label: 'Consistency', value: 'Strong' },
    ],
    tags: ['Java', 'Raft', 'gRPC', 'Docker', 'Distributed Systems'],
    github: 'https://github.com/MustakimFS/distributed-kv-store',
    featured: true,
    category: 'Distributed Systems',
  },
  {
    id: 'semiconductor',
    title: 'Semiconductor Yield Predictor',
    subtitle: 'Random Forest · L1 Selection · Streamlit',
    description: 'Binary classification system for predicting semiconductor wafer pass/fail on a severely imbalanced dataset. Two-stage pipeline using L1 regularization for dimensionality reduction followed by Random Forest with balanced class weighting.',
    metrics: [
      { label: 'Recall', value: '76%' },
      { label: 'ROC-AUC', value: '0.81' },
      { label: 'Features', value: '590→113' },
    ],
    tags: ['Python', 'scikit-learn', 'Streamlit', 'SECOM', 'ML'],
    github: 'https://github.com/MustakimFS/semiconductor-yield-optimizer',
    demo: null,
    featured: true,
    category: 'Machine Learning',
    paper: '/papers/semiconductor-yield.pdf',
  },
  {
    id: 'pixeldrive',
    title: 'PixelDrive: Road Scene Segmentation',
    subtitle: 'U-Net · SegNet · DeepLabV3+ · TensorFlow',
    description: 'Semantic segmentation of road scenes for autonomous driving. Trained and compared three architectures — U-Net, SegNet, and DeepLabV3+ — on the Lyft/Udacity Carla simulator dataset (13 semantic classes). Fixed 7 critical bugs in the original codebase including broken IoU metric, mask decoding, and softmax/logits mismatch.',
    metrics: [
      { label: 'mIoU', value: '95.50%' },
      { label: 'Inference', value: '45 FPS' },
      { label: 'Classes', value: '13' },
    ],
    tags: ['Python', 'TensorFlow', 'Keras', 'U-Net', 'DeepLabV3+', 'CV'],
    github: 'https://github.com/MustakimFS/pixeldrive-segmentation',
    demo: null,
    paper: '/papers/pixeldrive.pdf',
    featured: false,
    category: 'Computer Vision',
  },
  {
    id: 'missing-persons',
    title: 'Missing Persons Knowledge Graph',
    subtitle: 'RDF · SPARQL · FastAPI · React',
    description: 'Knowledge graph integrating 10,000+ NamUs records using semantic web technologies. Replaced a $50/month GraphDB/Azure backend with FastAPI + RDFLib achieving sub-100ms SPARQL queries at zero infrastructure cost.',
    metrics: [
      { label: 'Records', value: '10K+' },
      { label: 'Query latency', value: '<100ms' },
      { label: 'Infra cost', value: '$0' },
    ],
    tags: ['RDF', 'SPARQL', 'FastAPI', 'React', 'Ontology', 'Python'],
    github: 'https://github.com/MustakimFS',
    demo: 'https://missing-persons-knowledge-graph.vercel.app/',
    ieee: 'https://ieeexplore.ieee.org/document/11126748',
    featured: false,
    category: 'Research / Full Stack',
    paper: '/papers/missing-persons-kg.pdf',
  },
  {
    id: 'genome-assembler',
    title: 'De Bruijn Genome Assembler',
    subtitle: 'Java · Spring Boot · Graph Algorithms',
    description: 'Genome assembler achieving 99.9% coverage on phiX174 (5,386 bp) using de Bruijn graphs and Eulerian cycle traversal. Implemented error correction including tip removal and bubble detection with multi-format support.',
    metrics: [
      { label: 'Coverage', value: '99.9%' },
      { label: 'Genome', value: '5,386bp' },
      { label: 'Dataset', value: 'phiX174' },
    ],
    tags: ['Java', 'Spring Boot', 'React', 'Graph Algorithms', 'Bioinformatics'],
    github: 'https://github.com/MustakimFS',
    demo: 'https://debruijn-genome-assembler.vercel.app/',
    featured: false,
    category: 'Systems / Algorithms',
  },
]

export const SKILLS = [
  {
    category: 'Languages',
    items: [
      { name: 'Java', level: 90 },
      { name: 'Python', level: 92 },
      { name: 'TypeScript', level: 82 },
      { name: 'C++', level: 70 },
      { name: 'SQL', level: 78 },
    ],
  },
  {
    category: 'Backend & Systems',
    items: [
      { name: 'Spring Boot', level: 85 },
      { name: 'Django', level: 88 },
      { name: 'FastAPI', level: 85 },
      { name: 'gRPC', level: 78 },
      { name: 'Raft Consensus', level: 75 },
    ],
  },
  {
    category: 'AI / ML',
    items: [
      { name: 'LangChain / LangGraph', level: 88 },
      { name: 'scikit-learn', level: 87 },
      { name: 'PyTorch', level: 72 },
      { name: 'RAG Pipelines', level: 90 },
      { name: 'Knowledge Graphs', level: 80 },
    ],
  },
  {
    category: 'Frontend',
    items: [
      { name: 'React', level: 85 },
      { name: 'Next.js', level: 78 },
      { name: 'Tailwind CSS', level: 82 },
      { name: 'Streamlit', level: 88 },
    ],
  },
  {
    category: 'Data & Infra',
    items: [
      { name: 'MongoDB', level: 85 },
      { name: 'PostgreSQL', level: 78 },
      { name: 'Docker', level: 80 },
      { name: 'Redis', level: 72 },
      { name: 'Kafka', level: 68 },
    ],
  },
]

export const ACHIEVEMENTS = [
  { label: 'LeetCode Problems', value: '815+', sub: 'Top 15% globally · 126 Hard', href: 'https://leetcode.com/u/Mustakim_Shikalgar/' },
  { label: 'IEEE Paper', value: 'COMPSAC 2025', sub: '27% acceptance rate · Toronto', href: 'https://ieeexplore.ieee.org/document/11126748' },
  { label: 'GPA', value: '3.75', sub: 'MS Software Engineering · ASU', href: '#about' },
  { label: 'LLM Cost Cut', value: '85%', sub: '$0.0008/query · METY Legal', href: '#projects' },
]
