export const PERSONAL = {
  name: 'Mustakim Shikalgar',
  title: 'Software Engineer',
  tagline: 'Building distributed systems and intelligent applications.',
  bio: 'MS Software Engineering student at Arizona State University (GPA 3.75), graduating May 2026. Published IEEE researcher, Technical Architecture Lead, and top 15% LeetCode solver. I work at the intersection of distributed systems, machine learning, and full-stack engineering.',
  email: 'shikalgar.mustakim@gmail.com',
  linkedin: 'https://www.linkedin.com/in/mustakim-shikalgar',
  github: 'https://github.com/MustakimFS',
  leetcode: 'https://leetcode.com/u/Mustakim_Shikalgar/',
  ieee: 'https://ieeexplore.ieee.org/document/11126748',
  resume: '/resume.pdf',
  location: 'Tempe, Arizona',
}

export const PROJECTS = [
  {
    id: 'mety-legal',
    title: 'METY Legal Chatbot',
    subtitle: 'LangGraph · FastAPI · Django · 5-node pipeline',
    blurb: "Personalized AI legal assistant that knows what you don't know.",
    description: "A personalized legal chatbot with three modes — a guided chat that profiles each user's knowledge gaps and targets responses to their Most Critical Gap, a progressive course system across 20 legal topics at three difficulty levels, and a document generation mode that produces tailored legal PDFs through a lawyer-style conversational intake. METY builds an implicit knowledge profile from every conversation using a 4-dimension FSPR framework (Facts, Strategies, Procedures, Rationales) and targets every response to close the specific gap that matters most to that user. Architected as a privacy-first two-layer system: Django owns state and data, FastAPI is stateless and has zero database credentials. Rebuilt a 6-node LangGraph pipeline into a 5-node linear topology, dropped per-query LLM cost 82% ($0.024 → $0.0044), and added implicit FSPR inference on every message with zero user-facing latency via daemon-thread background work.",
    metrics: [
      { label: 'LLM cost reduction', value: '82%' },
      { label: 'User modes', value: '3' },
      { label: 'Legal topics', value: '20' },
    ],
    tags: ['LLM Systems', 'LangGraph', 'Distributed Architecture', 'FastAPI', 'Django', 'RAG', 'Python'],
    github: null,
    demo: null,
    featured: true,
    category: 'AI / Full Stack',
    year: '2026',
    note: 'Industry capstone · IP owned by MyEdMaster · Source under NDA',
    mockupUrl: 'mety.legal',
    videoUrl: '/projects/mety-legal/broque_demo.mp4',
  },
  {
    id: 'aegisflow',
    title: 'AegisFlow',
    subtitle: 'Reliability infrastructure for LLM pipelines',
    blurb: 'Reliability infrastructure for LLM pipelines — scoring, fallback, and chaos.',
    description: "AegisFlow is a reliability and orchestration layer that sits between an application and any LLM provider. Every model output passes through a four-axis confidence scorer (structural validity + semantic grounding + validator critique + provider history) combined with a diminishing-returns anomaly penalty into a single [0, 1] score. Based on the score, the system decides whether to accept, repair, retry with the same provider, fall back to a different one, or reject outright — without the calling application needing to know any of it. Decomposed into seven independent microservices (gateway, orchestrator, reliability, guardrails, memory, replay, chaos) each with its own API surface, Dockerfile, and Prometheus metrics; full 14-service stack (custom + infra) boots in a single docker compose up. Includes a chaos service that injects six failure modes — latency spikes, timeouts, synthetic 5xx errors, malformed JSON, hallucinations, and refusals — on any provider, without touching provider code.",
    metrics: [
      { label: 'Microservices', value: '7' },
      { label: 'Confidence model', value: '4-axis' },
      { label: 'Chaos failure modes', value: '6' },
    ],
    tags: ['Python 3.12', 'FastAPI', 'NATS JetStream', 'PostgreSQL / pgvector', 'Redis', 'Docker / Kubernetes', 'OpenTelemetry', 'Prometheus', 'Grafana', 'Tempo', 'Chaos Engineering'],
    github: 'https://github.com/MustakimFS/aegisflow',
    featured: true,
    category: 'Distributed Systems / LLM Infrastructure',
    year: '2026',
    mockupUrl: 'aegisflow.dev',
  },
  {
    id: 'missing-persons',
    title: 'Missing Persons Knowledge Graph',
    subtitle: 'OWL · RDFLib · SPARQL · FastAPI · React · IEEE COMPSAC 2025',
    blurb: 'An OWL/SPARQL knowledge graph over 3,559 NamUs cases — published at IEEE COMPSAC 2025.',
    description: 'Knowledge graph over 3,559 NamUs missing-persons cases across California, Texas, and Alaska, modeled in a custom OWL ontology and served via in-process rdflib. Replaced the original $50/month GraphDB/Azure backend with FastAPI + RDFLib achieving sub-100ms SPARQL queries at $0/month operating cost on Vercel + Render free tiers. Published at IEEE COMPSAC 2025 (Toronto, 27% acceptance rate) as "Enhanced Tracking and Reporting of Missing Persons Using Semantic Web Technologies".',
    metrics: [
      { label: 'NamUs cases', value: '3,559' },
      { label: 'Query latency', value: '<100ms' },
      { label: 'Infra cost', value: '$0/mo' },
    ],
    tags: ['RDF', 'OWL', 'SPARQL', 'RDFLib', 'FastAPI', 'React', 'Vite', 'NamUs', 'Python'],
    github: 'https://github.com/MustakimFS/missing-persons-knowledge-graph',
    demo: 'https://missing-persons-knowledge-graph.vercel.app/',
    ieee: 'https://ieeexplore.ieee.org/document/11126748',
    featured: true,
    category: 'Research / Knowledge Graph',
    year: '2024',
    mockupUrl: 'missing-persons-knowledge-graph.vercel.app',
    tint: 'asu',
    paper: '/papers/missing-persons-kg.pdf',
  },
  {
    id: 'distributed-kv',
    title: 'Distributed Key-Value Store',
    subtitle: 'Raft · gRPC · Protocol Buffers · Java 17 · Docker Compose',
    blurb: 'Paper-faithful Raft in Java — 17,857 ops/sec, sub-1 ms p99, survives 2-of-5 node failures.',
    description: 'Fault-tolerant 5-node KV store implementing Raft from the original paper. Tunable consistency via a single client argument (STRONG = linearizable / EVENTUAL = AP). Measured at 17,857 ops/sec throughput, p99 strong-read latency under 1 ms, leader election under 300 ms, and zero data loss with 2 of 5 nodes failed simultaneously. The whole 5-node cluster boots on Docker Compose with one shell call.',
    metrics: [
      { label: 'Throughput', value: '17,857 ops/s' },
      { label: 'Strong-read p99', value: '<1ms' },
      { label: 'Failures tolerated', value: '2 / 5' },
    ],
    tags: ['Java 17', 'Raft', 'gRPC', 'Protocol Buffers', 'Docker', 'Maven', 'Distributed Systems'],
    github: 'https://github.com/MustakimFS/distributed-kv-store',
    featured: true,
    category: 'Distributed Systems',
    year: '2026',
    mockupKind: 'terminal',
    tint: 'forest',
  },
  {
    id: 'semiconductor',
    title: 'Semiconductor Yield Predictor',
    subtitle: 'L1 + Random Forest · scikit-learn · Streamlit · UCI SECOM',
    blurb: 'Catches 76% of wafer failures on a 14:1-imbalanced dataset — beats four baselines including XGBoost + SMOTE.',
    description: 'Binary pass/fail prediction on UCI SECOM (1,567 wafers × 590 sensors, ~6% failure rate). Five-model comparison: from a naive logistic regression baseline (14% recall on the failure class) through cost-sensitive LogReg, random oversampling, and XGBoost + SMOTE — to the winning L1 + Random Forest pipeline at 76% recall and 0.81 ROC-AUC. Ships as a Streamlit operator UI with a live decision-threshold slider so the cost-asymmetry stays editable in the field.',
    metrics: [
      { label: 'Recall (failure class)', value: '76%' },
      { label: 'ROC-AUC', value: '0.81' },
      { label: 'Features pruned', value: '590 → 113' },
    ],
    tags: ['Python', 'scikit-learn', 'Random Forest', 'L1 / Lasso', 'imbalanced-learn', 'Streamlit', 'SECOM', 'ML'],
    github: 'https://github.com/MustakimFS/semiconductor-yield-optimizer',
    demo: null,
    featured: true,
    category: 'Machine Learning',
    year: '2025',
    mockupUrl: 'localhost:8501/secom',
    tint: 'warm',
    paper: '/papers/semiconductor-yield.pdf',
  },
  {
    id: 'pixeldrive',
    title: 'PixelDrive: Road Scene Segmentation',
    subtitle: 'U-Net · SegNet · DeepLabV3+ · TensorFlow · Hugging Face Spaces',
    blurb: 'Three segmentation models compared honestly — U-Net wins 79.33% mIoU on Carla, live on Hugging Face.',
    description: 'Semantic segmentation of road scenes for autonomous driving on the Lyft / Udacity Carla simulator dataset (13 classes). Trained and benchmarked three architectures end-to-end on identical pipelines — U-Net, SegNet, DeepLabV3+ — after first fixing 7 correctness bugs in the inherited baseline (broken mIoU implementation, softmax/logits mismatch, wrong-channel mask decode, et al). U-Net won at 79.33% mIoU and ships as a live Gradio Space at huggingface.co/spaces/mustakimfs/pixelDrive.',
    metrics: [
      { label: 'Mean IoU (U-Net)', value: '79.33%' },
      { label: 'Architectures', value: '3' },
      { label: 'Bugs fixed', value: '7' },
    ],
    tags: ['Python', 'TensorFlow', 'Keras', 'U-Net', 'SegNet', 'DeepLabV3+', 'Gradio', 'Hugging Face', 'CV'],
    github: 'https://github.com/MustakimFS/pixeldrive-segmentation',
    demo: 'https://huggingface.co/spaces/mustakimfs/pixelDrive',
    paper: '/papers/pixeldrive.pdf',
    featured: true,
    category: 'Computer Vision',
    year: '2025',
    mockupUrl: 'huggingface.co/spaces/mustakimfs/pixelDrive',
    tint: 'plum',
  },
  {
    id: 'genome-assembler',
    title: 'De Bruijn Genome Assembler',
    subtitle: "Java 17 · Spring Boot · Hierholzer's · React · Vite · phi X174",
    blurb: 'De Bruijn graph + iterative Eulerian traversal — 33,609 reads → 5,396 bp at 99.9% coverage in ~2 seconds.',
    description: 'Genome assembly toolkit implementing de Bruijn graph construction, iterative Hierholzer’s Eulerian-cycle traversal, tip removal, and bubble resolution — all hand-rolled in Java 17, no library shortcuts. Validates on the phi X174 bacteriophage (5,386 bp reference, 33,609 reads, ~111K-edge graph) at 99.9% coverage in ~2 seconds. Same jar drives a CLI and a Spring Boot REST API; a React + Vite frontend lets non-engineers drag-and-drop a FASTA file. Live at debruijn-genome-assembler.vercel.app.',
    metrics: [
      { label: 'Coverage (phi X174)', value: '99.9%' },
      { label: 'Input reads', value: '33,609' },
      { label: 'Assembly runtime', value: '~2 s' },
    ],
    tags: ['Java 17', 'Spring Boot 3', 'Maven', "Hierholzer's", 'de Bruijn graphs', 'React', 'Vite', 'Docker', 'Bioinformatics'],
    github: 'https://github.com/MustakimFS/debruijn-genome-assembler',
    demo: 'https://debruijn-genome-assembler.vercel.app/',
    featured: false,
    category: 'Systems / Algorithms',
    year: '2022',
    mockupKind: 'terminal',
    mockupUrl: 'debruijn-genome-assembler.vercel.app',
    tint: 'forest',
  },
  {
    id: 'launch-parameters',
    title: 'Launch Parameters',
    subtitle: 'Three.js · React · TypeScript · Python · Orbital Mechanics',
    blurb: 'Interactive launch planning from any point on Earth.',
    description: 'Launch Parameters is an orbital launch-planning tool where a user clicks any point on Earth and gets mission estimates for reaching orbit or departing toward another planet. It calculates launch azimuth, Earth-rotation assist, delta-v, propellant mass, launch windows, and trajectory geometry from location, payload, destination, and vehicle settings.',
    metrics: [
      { label: 'Local test suite', value: '102 tests' },
      { label: 'Launch selection', value: 'Any lat/lon point' },
      { label: 'Dashboard outputs', value: '6 CSV datasets' },
    ],
    tags: ['Orbital Mechanics', 'React', 'TypeScript', 'Three.js', 'Python', 'Data Visualization', 'Power BI'],
    github: 'https://github.com/MustakimFS/launch-parameters',
    demo: null,
    featured: true,
    category: 'Orbital Mechanics / Data Viz',
    year: '2023',
    mockupUrl: 'launch-parameters.local',
    tint: 'stadia',
  },
  {
    id: 'job-hunt',
    title: 'Job Hunt Dashboard',
    subtitle: 'Electron 29 · Node 18+ · Gmail OAuth · Gemini / Claude / OpenAI · Wallpaper Engine',
    blurb: 'Local-first Electron tray app — Gmail sync, BYOK multi-LLM classification, and a live Wallpaper Engine dashboard.',
    description: "A local-first job-application tracker built for personal use during the spring 2026 search. Electron 29 desktop app that lives in the Windows tray, syncs Gmail every N minutes on a read-only OAuth scope, and optionally classifies job-related emails through a pluggable AI provider (Gemini / Anthropic / OpenAI — BYOK, raw HTTPS, no SDKs). Storage is a JSON file in app.getPath('userData') — nothing leaves the machine except the Gmail OAuth call and the opt-in subject + snippet sent to the active LLM. A Wallpaper Engine 'Web' wallpaper at wallpaper/wallpaper.html mirrors the app state over a local WebSocket (ws://127.0.0.1:49152) so daily tasks and sync status are visible even when the app is collapsed to tray.",
    metrics: [
      { label: 'AI providers (BYOK)', value: '3' },
      { label: 'Servers', value: '0 · local-only' },
      { label: 'Wallpaper transport', value: 'ws://127.0.0.1:49152' },
    ],
    tags: ['Electron 29', 'Node.js 18', 'Gmail OAuth', 'node-cron', 'WebSocket', 'Gemini', 'Anthropic', 'OpenAI', 'Wallpaper Engine'],
    github: 'https://github.com/MustakimFS/electron-job-tracker',
    demo: null,
    featured: false,
    category: 'Desktop / Productivity',
    year: '2026',
    mockupUrl: 'localhost · tray app',
    tint: 'warm',
  },
  {
    id: 'zebradoodle',
    title: 'Zebradoodle',
    subtitle: 'React 17 · React Router · Wordle / Quordle / Sedecordle / Nerdle',
    blurb: 'Four daily puzzle modes sharing one two-pass scoring core — ported from a 2022 Java CLI to a static React bundle.',
    description: 'A browser word and math puzzle collection reconstructed from a 2022 Java CLI prototype I wrote in undergrad. Four game modes share one engine: Wordle (1 board), Quordle (4 boards), Sedecordle (16 boards, 21 guesses), and Nerdle (8-character math equation). Every day picks the same puzzle for everyone via a deterministic FNV-32 date hash; practice mode rolls a fresh puzzle on demand. Scoring is a JS port of the original Java compare() method, two-pass with proper repeated-letter handling. The Nerdle module ships its own tokenizer and evaluator that enforces operator precedence, exact integer division, and no-leading-zero rules. Stats, streaks, and daily-resume live in localStorage so the whole thing deploys as a static bundle.',
    metrics: [
      { label: 'Game modes', value: '4' },
      { label: 'Word bank', value: '14.8K' },
      { label: 'Backend services', value: '0' },
    ],
    tags: ['React 17', 'React Router 5', 'JavaScript', 'CRA', 'plain CSS', 'localStorage', 'canvas-confetti'],
    github: 'https://github.com/MustakimFS/zebradoodle',
    demo: 'https://mustakimfs.github.io/zebradoodle/',
    featured: false,
    category: 'Web / Games',
    playable: true,
  },
]

export const SKILLS = [
  {
    category: 'Languages',
    items: [
      { name: 'Java', level: 92 },
      { name: 'Python', level: 85 },
      { name: 'TypeScript', level: 82 },
      { name: 'C++', level: 70 },
      { name: 'SQL', level: 78 },
    ],
  },
  {
    category: 'Backend & Systems',
    items: [
      { name: 'Spring Boot', level: 85 },
      { name: 'Django', level: 88 },
      { name: 'FastAPI', level: 85 },
      { name: 'gRPC', level: 78 },
      { name: 'Raft Consensus', level: 75 },
    ],
  },
  {
    category: 'AI / ML',
    items: [
      { name: 'LangChain / LangGraph', level: 88 },
      { name: 'scikit-learn', level: 87 },
      { name: 'PyTorch', level: 72 },
      { name: 'RAG Pipelines', level: 90 },
      { name: 'Knowledge Graphs', level: 80 },
    ],
  },
  {
    category: 'Frontend',
    items: [
      { name: 'React', level: 85 },
      { name: 'Next.js', level: 78 },
      { name: 'Tailwind CSS', level: 82 },
      { name: 'Streamlit', level: 88 },
    ],
  },
  {
    category: 'Data & Infra',
    items: [
      { name: 'MongoDB', level: 85 },
      { name: 'PostgreSQL', level: 78 },
      { name: 'Docker', level: 80 },
      { name: 'Redis', level: 72 },
      { name: 'Kafka', level: 68 },
    ],
  },
]

export const ACHIEVEMENTS = [
  { label: 'LeetCode Contest Rating', value: '1841', sub: 'Top 6.44% globally', href: 'https://leetcode.com/u/Mustakim_Shikalgar/' },
  { label: 'IEEE Paper', value: 'COMPSAC 2025', sub: '27% acceptance rate · Toronto', href: 'https://ieeexplore.ieee.org/document/11126748' },
  { label: 'GPA', value: '3.75', sub: 'MS Software Engineering · ASU', href: '#about' },
  { label: 'LLM Cost Cut', value: '85%', sub: '$0.0008/query · METY Legal', href: '#projects' },
]
