export const PERSONAL = {
  name: 'Mustakim Shikalgar',
  title: 'Software Engineer',
  tagline: 'Building distributed systems and intelligent applications.',
  bio: 'MS Software Engineering student at Arizona State University (GPA 3.75), graduating May 2026. Published IEEE researcher, Technical Architecture Lead, and top 15% LeetCode solver. I work at the intersection of distributed systems, machine learning, and full-stack engineering.',
  email: 'shikalgar.mustakim@gmail.com',
  linkedin: 'https://www.linkedin.com/in/mustakim-shikalgar',
  github: 'https://github.com/MustakimFS',
  leetcode: 'https://leetcode.com/u/Mustakim_Shikalgar/',
  ieee: 'https://ieeexplore.ieee.org/document/11126748',
  resume: '/resume.pdf',
  location: 'Tempe, Arizona',
}

export const PROJECTS = [
  {
    id: 'mety-legal',
    title: 'METY Legal Chatbot',
    subtitle: 'LangGraph · Django · React · FastAPI',
    description: 'AI-powered personalized legal assistant (industry capstone, contract) with three distinct user modes across a distributed Django, React, FastAPI, LangGraph, and MongoDB stack. Served as Technical Architecture Lead for a 6-person cross-functional team across 7 sprints. Designed a dynamic FSPR knowledge profiling system that builds implicit user knowledge profiles through async background inference, targeting every response to each user\'s Most Critical Knowledge Gap. Architected a privacy-first two-layer system separating data orchestration from a stateless AI service enabling independent horizontal scaling, with Nginx reverse proxy for HTTPS termination and load balancing, Gunicorn multi-worker Django, Uvicorn-served FastAPI replicas behind a load balancer, and Celery with Redis for fault-tolerant background task queuing replacing Python threads. Rebuilt the LangGraph reasoning pipeline reducing cost by 85% to $0.0008 per query. Engineered token-aware rolling summarization for coherent long-session context retention and implemented lawyer-style intake behavior, context-aware legal document generation, parallel multi-dimension self-assessment evaluation, and a progressive course system spanning 9 legal domains.',
    metrics: [
      { label: 'Cost per query', value: '$0.0008' },
      { label: 'Cost reduction', value: '85%' },
      { label: 'Legal domains', value: '9' },
      { label: "User modes", value: "3" }
    ],
    tags: ["LangGraph", "Django", "React", "FastAPI", "MongoDB", "GPT-4o", "GPT-4o-mini", "Python"],
    github: null,
    demo: null,
    featured: true,
    category: 'AI / Full Stack',
    note: 'Industry capstone · Private contract · Source under NDA',
  },
  {
    id: 'aegisflow',
    title: 'AegisFlow',
    subtitle: 'FastAPI · NATS JetStream · pgvector · OpenTelemetry',
    description: 'Production-grade AI reliability platform that treats every agent invocation as a probabilistic operation requiring scoring, validation, recovery, and tracing. Seven decoupled microservices (gateway, orchestrator, reliability engine, guardrail layer, semantic memory, replay engine, and chaos injector) communicate over a NATS JetStream event bus with shared Postgres, pgvector, and Redis state. The reliability engine combines per-provider circuit breakers, confidence scoring, hallucination heuristics, and adaptive fallback routing to recover non-deterministically failing agents without human intervention. Every execution is event-sourced for deterministic replay: given a trace ID and a frozen model snapshot the system reproduces any historical run bit-for-bit. Full OpenTelemetry, Prometheus, and Grafana observability stack with a chaos engine that injects latency, malformed outputs, and provider outages on demand.',
    metrics: [
      { label: 'Microservices', value: '7' },
      { label: 'Min confidence', value: '0.75' },
      { label: 'Retry depth', value: '3×' },
    ],
    tags: ['Python', 'FastAPI', 'NATS', 'pgvector', 'OpenTelemetry', 'Docker', 'Kubernetes', 'Redis', 'PostgreSQL'],
    github: 'https://github.com/MustakimFS/aegisflow',
    featured: true,
    category: 'Distributed Systems',
  },
  {
    id: 'distributed-kv',
    title: 'Distributed Key-Value Store',
    subtitle: 'Raft Consensus · gRPC · Java · Docker',
    description: 'Fault-tolerant distributed KV store implementing Raft consensus for leader election and log replication across a 5-node cluster. Tunable consistency supporting CP vs AP trade-offs via configurable quorum-based reads.',
    metrics: [
      { label: 'Cluster nodes', value: '5' },
      { label: 'Read latency', value: '<10ms' },
      { label: 'Consistency', value: 'Strong' },
    ],
    tags: ['Java', 'Raft', 'gRPC', 'Docker', 'Distributed Systems'],
    github: 'https://github.com/MustakimFS/distributed-kv-store',
    featured: true,
    category: 'Distributed Systems',
  },
  {
    id: 'semiconductor',
    title: 'Semiconductor Yield Predictor',
    subtitle: 'Random Forest · L1 Selection · Streamlit',
    description: 'Binary classification system for predicting semiconductor wafer pass/fail on a severely imbalanced dataset. Two-stage pipeline using L1 regularization for dimensionality reduction followed by Random Forest with balanced class weighting.',
    metrics: [
      { label: 'Recall', value: '76%' },
      { label: 'ROC-AUC', value: '0.81' },
      { label: 'Features', value: '590→113' },
    ],
    tags: ['Python', 'scikit-learn', 'Streamlit', 'SECOM', 'ML'],
    github: 'https://github.com/MustakimFS/semiconductor-yield-optimizer',
    demo: null,
    featured: true,
    category: 'Machine Learning',
    paper: '/papers/semiconductor-yield.pdf',
  },
  {
    id: 'pixeldrive',
    title: 'PixelDrive: Road Scene Segmentation',
    subtitle: 'U-Net · SegNet · DeepLabV3+ · TensorFlow',
    description: 'Semantic segmentation of road scenes for autonomous driving. Trained and compared three architectures — U-Net, SegNet, and DeepLabV3+ — on the Lyft/Udacity Carla simulator dataset (13 semantic classes). Fixed 7 critical bugs in the original codebase including broken IoU metric, mask decoding, and softmax/logits mismatch.',
    metrics: [
      { label: 'mIoU', value: '95.50%' },
      { label: 'Inference', value: '45 FPS' },
      { label: 'Classes', value: '13' },
    ],
    tags: ['Python', 'TensorFlow', 'Keras', 'U-Net', 'DeepLabV3+', 'CV'],
    github: 'https://github.com/MustakimFS/pixeldrive-segmentation',
    demo: 'https://huggingface.co/spaces/mustakimfs/pixelDrive',
    paper: '/papers/pixeldrive.pdf',
    featured: false,
    category: 'Computer Vision',
  },
  {
    id: 'missing-persons',
    title: 'Missing Persons Knowledge Graph',
    subtitle: 'RDF · SPARQL · FastAPI · React',
    description: 'Knowledge graph integrating 10,000+ NamUs records using semantic web technologies. Replaced a $50/month GraphDB/Azure backend with FastAPI + RDFLib achieving sub-100ms SPARQL queries at zero infrastructure cost.',
    metrics: [
      { label: 'Records', value: '10K+' },
      { label: 'Query latency', value: '<100ms' },
      { label: 'Infra cost', value: '$0' },
    ],
    tags: ['RDF', 'SPARQL', 'FastAPI', 'React', 'Ontology', 'Python'],
    github: 'https://github.com/MustakimFS',
    demo: 'https://missing-persons-knowledge-graph.vercel.app/',
    ieee: 'https://ieeexplore.ieee.org/document/11126748',
    featured: false,
    category: 'Research / Full Stack',
    paper: '/papers/missing-persons-kg.pdf',
  },
  {
    id: 'genome-assembler',
    title: 'De Bruijn Genome Assembler',
    subtitle: 'Java · Spring Boot · Graph Algorithms',
    description: 'Genome assembler achieving 99.9% coverage on phiX174 (5,386 bp) using de Bruijn graphs and Eulerian cycle traversal. Implemented error correction including tip removal and bubble detection with multi-format support.',
    metrics: [
      { label: 'Coverage', value: '99.9%' },
      { label: 'Genome', value: '5,386bp' },
      { label: 'Dataset', value: 'phiX174' },
    ],
    tags: ['Java', 'Spring Boot', 'React', 'Graph Algorithms', 'Bioinformatics'],
    github: 'https://github.com/MustakimFS',
    demo: 'https://debruijn-genome-assembler.vercel.app/',
    featured: false,
    category: 'Systems / Algorithms',
  },
  {
    id: 'zebradoodle',
    title: 'Zebradoodle',
    subtitle: 'React · Wordle / Quordle / Sedecordle / Nerdle',
    description: 'A browser word and math puzzle collection reconstructed from a 2022 Java CLI prototype I wrote in undergrad. Four game modes share one engine: Wordle (1 board), Quordle (4 boards), Sedecordle (16 boards, 21 guesses), and Nerdle (8-character math equation). Every day picks the same puzzle for everyone via a deterministic FNV-32 date hash; practice mode rolls a fresh puzzle on demand. Scoring is a JS port of the original Java compare() method, two-pass with proper repeated-letter handling. The Nerdle module ships its own tokenizer and evaluator that enforces operator precedence, exact integer division, and no-leading-zero rules. Stats, streaks, and daily-resume live in localStorage so the whole thing deploys as a static bundle.',
    metrics: [
      { label: 'Game modes', value: '4' },
      { label: 'Word bank', value: '14.8K' },
      { label: 'Original', value: '2022' },
    ],
    tags: ['React 17', 'JavaScript', 'React Router', 'CSS', 'localStorage', 'canvas-confetti'],
    github: 'https://github.com/MustakimFS/zebradoodle',
    demo: 'https://mustakimfs.github.io/zebradoodle/',
    featured: false,
    category: 'Web / Games',
    playable: true,
  },
]

export const SKILLS = [
  {
    category: 'Languages',
    items: [
      { name: 'Java', level: 92 },
      { name: 'Python', level: 85 },
      { name: 'TypeScript', level: 82 },
      { name: 'C++', level: 70 },
      { name: 'SQL', level: 78 },
    ],
  },
  {
    category: 'Backend & Systems',
    items: [
      { name: 'Spring Boot', level: 85 },
      { name: 'Django', level: 88 },
      { name: 'FastAPI', level: 85 },
      { name: 'gRPC', level: 78 },
      { name: 'Raft Consensus', level: 75 },
    ],
  },
  {
    category: 'AI / ML',
    items: [
      { name: 'LangChain / LangGraph', level: 88 },
      { name: 'scikit-learn', level: 87 },
      { name: 'PyTorch', level: 72 },
      { name: 'RAG Pipelines', level: 90 },
      { name: 'Knowledge Graphs', level: 80 },
    ],
  },
  {
    category: 'Frontend',
    items: [
      { name: 'React', level: 85 },
      { name: 'Next.js', level: 78 },
      { name: 'Tailwind CSS', level: 82 },
      { name: 'Streamlit', level: 88 },
    ],
  },
  {
    category: 'Data & Infra',
    items: [
      { name: 'MongoDB', level: 85 },
      { name: 'PostgreSQL', level: 78 },
      { name: 'Docker', level: 80 },
      { name: 'Redis', level: 72 },
      { name: 'Kafka', level: 68 },
    ],
  },
]

export const ACHIEVEMENTS = [
  { label: 'LeetCode Problems', value: '815+', sub: 'Top 15% globally · 126 Hard', href: 'https://leetcode.com/u/Mustakim_Shikalgar/' },
  { label: 'IEEE Paper', value: 'COMPSAC 2025', sub: '27% acceptance rate · Toronto', href: 'https://ieeexplore.ieee.org/document/11126748' },
  { label: 'GPA', value: '3.75', sub: 'MS Software Engineering · ASU', href: '#about' },
  { label: 'LLM Cost Cut', value: '85%', sub: '$0.0008/query · METY Legal', href: '#projects' },
]
